# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

knn_rcpp <- function(data, k, nthreads = 0L) {
    .Call('_MEcell_knn_rcpp', PACKAGE = 'MEcell', data, k, nthreads)
}

find_knn_rcpp <- function(mat, candidates_mat) {
    .Call('_MEcell_find_knn_rcpp', PACKAGE = 'MEcell', mat, candidates_mat)
}

cal_mei_rcpp <- function(p, i_vec, x, cellcluster, topn) {
    .Call('_MEcell_cal_mei_rcpp', PACKAGE = 'MEcell', p, i_vec, x, cellcluster, topn)
}

