# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

find_knn_rcpp <- function(mat, candidates_mat) {
    .Call('_MEcell_find_knn_rcpp', PACKAGE = 'MEcell', mat, candidates_mat)
}

